name: Pull Request Molecule Unit Tests for Ansible Role Senzing API

on:
  pull_request:
    branches:
      - master

jobs:
  prExecuteMoleculeUnitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Set Senzing EULA
      - name: Ansible Molecule
        uses: gofrolist/molecule-action@v2.0.0
        env:
          SENZING_EULA: ${{ secrets.SENZING_ACCEPT_EULA }}
